# Generated by Django 6.0.3 on 2026-03-27 07:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rigs_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('investments_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Profile',
                'verbose_name_plural': 'Financial Profiles',
            },
        ),
        migrations.CreateModel(
            name='MonthCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('emergency_fund_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rigs_fund_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('savings_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expenses_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('wants_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Month Cycle',
                'verbose_name_plural': 'Month Cycles',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AllocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_bucket', models.CharField(max_length=50)),
                ('to_bucket', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_logs', to='api.monthcycle')),
            ],
            options={
                'verbose_name': 'Allocation Log',
                'verbose_name_plural': 'Allocation Logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_fund', models.DecimalField(decimal_places=2, max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rigs_fund', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_on_hand', models.DecimalField(decimal_places=2, max_digits=14)),
                ('investments_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=14)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Net Worth Snapshot',
                'verbose_name_plural': 'Net Worth Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthcycle',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_user_year_month'),
        ),
    ]
