# Generated by Django 6.0.3 on 2026-03-26 05:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rigs_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('investments_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Profile',
                'verbose_name_plural': 'Financial Profiles',
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_fund', models.DecimalField(decimal_places=2, max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rigs_fund', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_on_hand', models.DecimalField(decimal_places=2, max_digits=14)),
                ('investments_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=14)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Net Worth Snapshot',
                'verbose_name_plural': 'Net Worth Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
    ]
