# Generated by Django 6.0.3 on 2026-05-29 14:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_investmentallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('system_required', 'System Required'), ('goal', 'Goal')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monthly_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('allocation_priority', models.PositiveIntegerField(default=999)),
                ('skip_on_low_income', models.BooleanField(default=False)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'ordering': ['allocation_priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudgetSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_monthly_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('needs_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('wants_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monthly Budget Setup',
                'verbose_name_plural': 'Monthly Budget Setups',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_type', models.CharField(choices=[('income_allocation', 'Income Allocation'), ('fund_to_cash', 'Fund to Cash'), ('cash_to_fund', 'Cash to Fund'), ('fund_to_fund', 'Fund to Fund'), ('external_add', 'External Add'), ('goal_completed', 'Goal Completed'), ('survival_draw', 'Survival Draw'), ('month_end_carry', 'Month End Carry')], max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='allocationlog',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='financialprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investmentallocation',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='monthcycle',
            name='unique_user_year_month',
        ),
        migrations.RemoveConstraint(
            model_name='monthsummary',
            name='unique_user_cycle_summary',
        ),
        migrations.RenameField(
            model_name='monthcycle',
            old_name='emergency_fund_budget',
            new_name='income_entered',
        ),
        migrations.RenameField(
            model_name='monthcycle',
            old_name='expenses_budget',
            new_name='needs_budget_used',
        ),
        migrations.RenameField(
            model_name='monthcycle',
            old_name='income',
            new_name='needs_spent',
        ),
        migrations.RenameField(
            model_name='monthcycle',
            old_name='rigs_fund_budget',
            new_name='wants_budget_used',
        ),
        migrations.RenameField(
            model_name='monthcycle',
            old_name='savings_budget',
            new_name='wants_spent',
        ),
        migrations.RenameField(
            model_name='monthsummary',
            old_name='remaining_carried_over',
            new_name='total_allocated_to_funds',
        ),
        migrations.RenameField(
            model_name='monthsummary',
            old_name='total_expenses',
            new_name='total_needs_spent',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='networthsnapshot',
            name='cash_on_hand',
        ),
        migrations.RemoveField(
            model_name='networthsnapshot',
            name='emergency_fund',
        ),
        migrations.RemoveField(
            model_name='networthsnapshot',
            name='investments_total',
        ),
        migrations.RemoveField(
            model_name='networthsnapshot',
            name='rigs_fund',
        ),
        migrations.RemoveField(
            model_name='networthsnapshot',
            name='savings',
        ),
        migrations.RemoveField(
            model_name='networthsnapshot',
            name='user',
        ),
        migrations.AddField(
            model_name='monthcycle',
            name='income_scenario',
            field=models.CharField(blank=True, choices=[('full', 'Full'), ('low', 'Low'), ('zero', 'Zero')], max_length=10),
        ),
        migrations.AddField(
            model_name='monthsummary',
            name='total_wants_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='networthsnapshot',
            name='snapshot_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('overspend', 'Overspend'), ('daily_limit', 'Daily Limit'), ('hard_stop', 'Hard Stop'), ('emergency_low', 'Emergency Low'), ('goal_behind', 'Goal Behind')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monthcycle',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.financialaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.financialaccount'),
        ),
        migrations.AddField(
            model_name='monthcycle',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_cycles', to='api.financialaccount'),
        ),
        migrations.AddField(
            model_name='monthsummary',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_summaries', to='api.financialaccount'),
        ),
        migrations.AddField(
            model_name='networthsnapshot',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to='api.financialaccount'),
        ),
        migrations.AddConstraint(
            model_name='monthsummary',
            constraint=models.UniqueConstraint(fields=('account', 'cycle'), name='unique_account_cycle_summary'),
        ),
        migrations.AddField(
            model_name='fund',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='api.financialaccount'),
        ),
        migrations.AddField(
            model_name='monthlybudgetsetup',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_setups', to='api.financialaccount'),
        ),
        migrations.AddField(
            model_name='monthcycle',
            name='budget_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_cycles', to='api.monthlybudgetsetup'),
        ),
        migrations.AddConstraint(
            model_name='monthcycle',
            constraint=models.UniqueConstraint(fields=('account', 'year', 'month'), name='unique_account_year_month'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='api.financialaccount'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='api.monthcycle'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='api.fund'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='api.fund'),
        ),
        migrations.DeleteModel(
            name='AllocationLog',
        ),
        migrations.DeleteModel(
            name='FinancialProfile',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentAllocation',
        ),
        migrations.RemoveField(
            model_name='monthcycle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthcycle',
            name='wants_budget',
        ),
        migrations.RemoveField(
            model_name='monthsummary',
            name='total_saved',
        ),
        migrations.RemoveField(
            model_name='monthsummary',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='fund',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_account_fund_name'),
        ),
    ]
